### ISSUE TITLE
keyboard_and_audio not working in notebook

### ISSUE THREAD

**Issue by thorwhalen** [i2mint/stream2py#13]
Running `keyboard_and_audio` in terminal works, but
when in (`DataSpell`) notebook, I get the following error.

```python
from stream2py.examples.usage.keyboard_and_audio import keyboard_and_audio

keyboard_and_audio()
```

Gets me too...

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/Users/Thor.Whalen/Dropbox/dev/p3/proj/i/stream2py/stream2py/utility/getch.py", line 11, in __init__
    self.impl = _GetchWindows(is_blocking)
  File "/Users/Thor.Whalen/Dropbox/dev/p3/proj/i/stream2py/stream2py/utility/getch.py", line 75, in __init__
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Thor.Whalen/.pyenv/versions/3.8.6/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/Thor.Whalen/Dropbox/dev/p3/proj/i/stream2py/stream2py/sources/keyboard_input.py", line 61, in run
    from stream2py.utility.getch import getch
  File "/Users/Thor.Whalen/Dropbox/dev/p3/proj/i/stream2py/stream2py/utility/getch.py", line 100, in <module>
    getch = _Getch()
  File "/Users/Thor.Whalen/Dropbox/dev/p3/proj/i/stream2py/stream2py/utility/getch.py", line 13, in __init__
    self.impl = _GetchUnix(is_blocking)
  File "/Users/Thor.Whalen/Dropbox/dev/p3/proj/i/stream2py/stream2py/utility/getch.py", line 27, in __init__
    self.old_settings = termios.tcgetattr(self.fd)
termios.error: (25, 'Inappropriate ioctl for device')
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202893062686134/1203423907692032) by [Unito](https://www.unito.io)

**Comment by andeaseme** [comment]
The same problem occurs when using in Pycharm IDE's built in terminal.  
`stream2py/utility/getch.py` only supports windows and unix terminals that support character captures with `msvcrt` or `termios` modules .  `_Getch` can be extended to support more if you want to look into it.  I don't know how much effort it will take.
